name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }} .

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }} \
          --region ${{ secrets.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8080
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
